### ISSUE TITLE
link error building Remotery for macOS with Xcode 14.3 beta

### ISSUE THREAD

**Issue by jwwalker** [OGRECave/ogre-next-deps#11]
When attempting to build the dependencies using Xcode 14.3 beta, I got an error:

```
ld: file not found: /Applications/Xcode14.3-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_macosx.a
```

This doesn't happen with Xcode 14.2.  As I understand it, libarclite has something to do with providing runtime compatibility for old versions of macOS.  So maybe the problem is that CMakeLists.txt sets `CMAKE_OSX_DEPLOYMENT_TARGET` to 10.7, while the minimum officially-supported deployment target for Xcode 14.2 and later is 10.13.

**Comment by darksylinc** [comment]
Since GL3+ is no longer used by us in Apple, we should just raise the min deployment target to the first macOS that came with Metal (IIRC El Capitan)

**Comment by jwwalker** [comment]
Wikipedia agrees that the first macOS with Metal was El Capitan (10.11).  And setting `CMAKE_OSX_DEPLOYMENT_TARGET` to 10.11 does make the build succeed with Xcode 14.3 beta.

**Comment by darksylinc** [comment]
Done.

Thanks!
