### ISSUE TITLE
Freeimage doesn't build with latest VS 2019 versions

### ISSUE THREAD

**Issue by TaaTT4** [OGRECave/ogre-next-deps#2]
With version 16.9.3 of VS 2019 (but I suspect with every version greater-equal than 16.8.x as well) Freeimage doesn't build in non-debug modes. The error is related to OpenJPEG library: https://github.com/uclouvain/openjpeg/issues/1333. For what I've understood, OpenJPEG 2.x versions aren't affected by this issue.
An Freeimage upgrade should hopefully fix the problem.

[Here](https://github.com/OGRECave/ogre-next-deps/files/6249507/patch.diff.txt) you can find a quick and dirty patch to ovverride the issue.

**Comment by Setz0r** [comment]
This is apparently due to a typo in opj_includes.h

https://github.com/OGRECave/ogre-next-deps/blob/master/src/FreeImage/Source/LibOpenJPEG/opj_includes.h#L91

changing it from "lrintf" to "lprintf" allows compilation

**Comment by darksylinc** [comment]
Someone posted here but removed it

However he gave useful information: Apparently `lrint` wasn't defined in MSVC but it may have been recently added, causing a clash
