### ISSUE TITLE
Compiler errors building FreeImage under Linux

### ISSUE THREAD

**Issue by resttime** [OGRECave/ogre-next-deps#6]
Following the instructions under: https://ogrecave.github.io/ogre-next/api/2.3/_setting_up_ogre_linux.html

Attempting to build dependencies under Linux results in compiler errors about ISO C++17 such as the following:

```
ogre-next-deps/src/FreeImage/Source/OpenEXR/Imath/ImathVec.h:227:41: error: ISO C++17 does not allow dynamic exception specifications
  227 |     const Vec2 &        normalizeExc () throw (Iex::MathExc);
```

**Comment by AllianceDarkSylinc** [comment]
Is this still an issue? I upgraded FreeImage 2 months ago but I think this problem persists.

**Comment by darksylinc** [comment]
Is this still an issue? I upgraded FreeImage 2 months ago but I think this problem persists.

**Comment by resttime** [comment]
Yeah, tried a new bulid just now. It'll pop up on Linux on distros that use more updated C++ compilers if building the Freeimage bundled in this dep folder instead of using the system distributed ones.

![image](https://user-images.githubusercontent.com/2598904/179298109-9f310e58-43e5-43cd-8d8e-0cd2ac0abbf4.png)

**Comment by darksylinc** [comment]
[Fixed](https://github.com/OGRECave/ogre-next-deps/pull/7#issuecomment-1972054701).
