### ISSUE TITLE
shaderc Link error when compiling INSTALL.sln

### ISSUE THREAD

**Issue by Al-Mostapha** [OGRECave/ogre-next-deps#8]
![image](https://user-images.githubusercontent.com/61952094/147511172-15065415-0e95-4081-bb43-0c6470d90c08.png)
i 
i get this error in both release and debug

**Comment by YuDe95** [comment]
do you solve it ?

**Comment by SKBotNL** [comment]
Read the README:
**Note: Python 3.X is required to build the "shaderc" project.** Download link: [Python 3.X](https://www.python.org/downloads/)

**Comment by LPsir** [comment]
i had install python ,bug error  still exists. who can help me?
![image](https://user-images.githubusercontent.com/67616537/179170850-b9c5ad30-afd2-4c66-91fa-20fb9339a57a.png)

**Comment by AllianceDarkSylinc** [comment]
As per the [README](https://github.com/OGRECave/ogre-next-deps#checkout) you need to clone the repo using:
`git clone --recurse-submodules --shallow-submodules https://github.com/OGRECave/ogre-next-deps`

This repo uses submodules and unfortunately git defaults to not cloning submodules.

**Comment by AllianceDarkSylinc** [comment]
As per the [README](https://github.com/OGRECave/ogre-next-deps#checkout) you need to clone the repo using:
`git clone --recurse-submodules --shallow-submodules https://github.com/OGRECave/ogre-next-deps`

This repo uses submodules and unfortunately git defaults to not cloning submodules.

**Comment by darksylinc** [comment]
If there are no other questions I'm closing this ticket due to inactivity.
